/**
 * Author : Asad Shahabuddin
 * File   : InputSplit.java
 * Email  : asad808@ccs.neu.edu
 * Created: Mar 24, 2015
 * Edited : Mar 25, 2015
 */


package com.rasp.mr;


import java.io.IOException;
import java.util.Map;

/**
 * this class represents the data generated by the {@link com.rasp.mr.MapperTask}
 */
public interface MapContext {

    /**
     * writes the key and value to a output stream
     *
     * @param key
     * @param value
     * @throws IOException
     */
    public void write(Writable key, Writable value) throws IOException;

    /**
     * Closing all the open connections
     */
    public void close() throws IOException;

    /**
     *
     * @return the frequency of the keys generated by the map
     */
    public Map<String,Long> getKeyCountMap();
    public void setKeyCountMap(Map<String,Long> keyCountMap);
}
