/**
 * Author : Asad Shahabuddin
 * File   : InputSplit.java
 * Email  : asad808@ccs.neu.edu
 * Created: Mar 24, 2015
 * Edited : Mar 25, 2015
 */

package com.rasp.mr;

import java.io.IOException;
import org.apache.commons.lang3.tuple.Pair;

/**
 * this class represents the data generated by the {@link com.rasp.mr.ReducerTask}
 */
public interface ReduceContext {

    /**
     * reads the data that is written by the Reducer
     *
     * @return a pair of key and value from the ReduceContext
     * @throws IOException
     */
    public Pair<Writable, Writable> read() throws IOException;

    /**
     * writes the key and value to an output stream
     * @param k
     * @param v
     * @throws IOException
     */
    public void write(Writable k, Writable v) throws IOException;

    /**
     * closes all connections
     * @throws IOException
     */
    public void close() throws IOException;
}