// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sinputsplit.proto

package com.rasp.fs;

public final class SInputSplitProtos {
  private SInputSplitProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SInputSplitOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.rasp.fs.protobuf.SInputSplit)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 idx = 1;</code>
     */
    boolean hasIdx();
    /**
     * <code>required int32 idx = 1;</code>
     */
    int getIdx();

    /**
     * <code>required int64 offset = 2;</code>
     */
    boolean hasOffset();
    /**
     * <code>required int64 offset = 2;</code>
     */
    long getOffset();

    /**
     * <code>required int64 length = 3;</code>
     */
    boolean hasLength();
    /**
     * <code>required int64 length = 3;</code>
     */
    long getLength();

    /**
     * <code>required string location = 4;</code>
     */
    boolean hasLocation();
    /**
     * <code>required string location = 4;</code>
     */
    java.lang.String getLocation();
    /**
     * <code>required string location = 4;</code>
     */
    com.google.protobuf.ByteString
        getLocationBytes();
  }
  /**
   * Protobuf type {@code com.rasp.fs.protobuf.SInputSplit}
   */
  public static final class SInputSplit extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.rasp.fs.protobuf.SInputSplit)
      SInputSplitOrBuilder {
    // Use SInputSplit.newBuilder() to construct.
    private SInputSplit(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SInputSplit(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SInputSplit defaultInstance;
    public static SInputSplit getDefaultInstance() {
      return defaultInstance;
    }

    public SInputSplit getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SInputSplit(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              idx_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              offset_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              length_ = input.readInt64();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              location_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rasp.fs.SInputSplitProtos.internal_static_com_rasp_fs_protobuf_SInputSplit_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rasp.fs.SInputSplitProtos.internal_static_com_rasp_fs_protobuf_SInputSplit_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rasp.fs.SInputSplitProtos.SInputSplit.class, com.rasp.fs.SInputSplitProtos.SInputSplit.Builder.class);
    }

    public static com.google.protobuf.Parser<SInputSplit> PARSER =
        new com.google.protobuf.AbstractParser<SInputSplit>() {
      public SInputSplit parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SInputSplit(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SInputSplit> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int IDX_FIELD_NUMBER = 1;
    private int idx_;
    /**
     * <code>required int32 idx = 1;</code>
     */
    public boolean hasIdx() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 idx = 1;</code>
     */
    public int getIdx() {
      return idx_;
    }

    public static final int OFFSET_FIELD_NUMBER = 2;
    private long offset_;
    /**
     * <code>required int64 offset = 2;</code>
     */
    public boolean hasOffset() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 offset = 2;</code>
     */
    public long getOffset() {
      return offset_;
    }

    public static final int LENGTH_FIELD_NUMBER = 3;
    private long length_;
    /**
     * <code>required int64 length = 3;</code>
     */
    public boolean hasLength() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 length = 3;</code>
     */
    public long getLength() {
      return length_;
    }

    public static final int LOCATION_FIELD_NUMBER = 4;
    private java.lang.Object location_;
    /**
     * <code>required string location = 4;</code>
     */
    public boolean hasLocation() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string location = 4;</code>
     */
    public java.lang.String getLocation() {
      java.lang.Object ref = location_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          location_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string location = 4;</code>
     */
    public com.google.protobuf.ByteString
        getLocationBytes() {
      java.lang.Object ref = location_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        location_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      idx_ = 0;
      offset_ = 0L;
      length_ = 0L;
      location_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasIdx()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOffset()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLength()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLocation()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, idx_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, offset_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, length_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getLocationBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, idx_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, offset_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, length_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getLocationBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.rasp.fs.SInputSplitProtos.SInputSplit parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rasp.fs.SInputSplitProtos.SInputSplit parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rasp.fs.SInputSplitProtos.SInputSplit parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rasp.fs.SInputSplitProtos.SInputSplit parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rasp.fs.SInputSplitProtos.SInputSplit parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.rasp.fs.SInputSplitProtos.SInputSplit parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.rasp.fs.SInputSplitProtos.SInputSplit parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.rasp.fs.SInputSplitProtos.SInputSplit parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.rasp.fs.SInputSplitProtos.SInputSplit parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.rasp.fs.SInputSplitProtos.SInputSplit parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.rasp.fs.SInputSplitProtos.SInputSplit prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.rasp.fs.protobuf.SInputSplit}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.rasp.fs.protobuf.SInputSplit)
        com.rasp.fs.SInputSplitProtos.SInputSplitOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.rasp.fs.SInputSplitProtos.internal_static_com_rasp_fs_protobuf_SInputSplit_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.rasp.fs.SInputSplitProtos.internal_static_com_rasp_fs_protobuf_SInputSplit_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.rasp.fs.SInputSplitProtos.SInputSplit.class, com.rasp.fs.SInputSplitProtos.SInputSplit.Builder.class);
      }

      // Construct using com.rasp.fs.SInputSplitProtos.SInputSplit.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        idx_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        offset_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        length_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        location_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.rasp.fs.SInputSplitProtos.internal_static_com_rasp_fs_protobuf_SInputSplit_descriptor;
      }

      public com.rasp.fs.SInputSplitProtos.SInputSplit getDefaultInstanceForType() {
        return com.rasp.fs.SInputSplitProtos.SInputSplit.getDefaultInstance();
      }

      public com.rasp.fs.SInputSplitProtos.SInputSplit build() {
        com.rasp.fs.SInputSplitProtos.SInputSplit result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.rasp.fs.SInputSplitProtos.SInputSplit buildPartial() {
        com.rasp.fs.SInputSplitProtos.SInputSplit result = new com.rasp.fs.SInputSplitProtos.SInputSplit(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.idx_ = idx_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.offset_ = offset_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.length_ = length_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.location_ = location_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.rasp.fs.SInputSplitProtos.SInputSplit) {
          return mergeFrom((com.rasp.fs.SInputSplitProtos.SInputSplit)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.rasp.fs.SInputSplitProtos.SInputSplit other) {
        if (other == com.rasp.fs.SInputSplitProtos.SInputSplit.getDefaultInstance()) return this;
        if (other.hasIdx()) {
          setIdx(other.getIdx());
        }
        if (other.hasOffset()) {
          setOffset(other.getOffset());
        }
        if (other.hasLength()) {
          setLength(other.getLength());
        }
        if (other.hasLocation()) {
          bitField0_ |= 0x00000008;
          location_ = other.location_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasIdx()) {
          
          return false;
        }
        if (!hasOffset()) {
          
          return false;
        }
        if (!hasLength()) {
          
          return false;
        }
        if (!hasLocation()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.rasp.fs.SInputSplitProtos.SInputSplit parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.rasp.fs.SInputSplitProtos.SInputSplit) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int idx_ ;
      /**
       * <code>required int32 idx = 1;</code>
       */
      public boolean hasIdx() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 idx = 1;</code>
       */
      public int getIdx() {
        return idx_;
      }
      /**
       * <code>required int32 idx = 1;</code>
       */
      public Builder setIdx(int value) {
        bitField0_ |= 0x00000001;
        idx_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 idx = 1;</code>
       */
      public Builder clearIdx() {
        bitField0_ = (bitField0_ & ~0x00000001);
        idx_ = 0;
        onChanged();
        return this;
      }

      private long offset_ ;
      /**
       * <code>required int64 offset = 2;</code>
       */
      public boolean hasOffset() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 offset = 2;</code>
       */
      public long getOffset() {
        return offset_;
      }
      /**
       * <code>required int64 offset = 2;</code>
       */
      public Builder setOffset(long value) {
        bitField0_ |= 0x00000002;
        offset_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 offset = 2;</code>
       */
      public Builder clearOffset() {
        bitField0_ = (bitField0_ & ~0x00000002);
        offset_ = 0L;
        onChanged();
        return this;
      }

      private long length_ ;
      /**
       * <code>required int64 length = 3;</code>
       */
      public boolean hasLength() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 length = 3;</code>
       */
      public long getLength() {
        return length_;
      }
      /**
       * <code>required int64 length = 3;</code>
       */
      public Builder setLength(long value) {
        bitField0_ |= 0x00000004;
        length_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 length = 3;</code>
       */
      public Builder clearLength() {
        bitField0_ = (bitField0_ & ~0x00000004);
        length_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object location_ = "";
      /**
       * <code>required string location = 4;</code>
       */
      public boolean hasLocation() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string location = 4;</code>
       */
      public java.lang.String getLocation() {
        java.lang.Object ref = location_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            location_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string location = 4;</code>
       */
      public com.google.protobuf.ByteString
          getLocationBytes() {
        java.lang.Object ref = location_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          location_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string location = 4;</code>
       */
      public Builder setLocation(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        location_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string location = 4;</code>
       */
      public Builder clearLocation() {
        bitField0_ = (bitField0_ & ~0x00000008);
        location_ = getDefaultInstance().getLocation();
        onChanged();
        return this;
      }
      /**
       * <code>required string location = 4;</code>
       */
      public Builder setLocationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        location_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.rasp.fs.protobuf.SInputSplit)
    }

    static {
      defaultInstance = new SInputSplit(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.rasp.fs.protobuf.SInputSplit)
  }

  public interface SInputChunkOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.rasp.fs.protobuf.SInputChunk)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required bytes chunk = 1;</code>
     */
    boolean hasChunk();
    /**
     * <code>required bytes chunk = 1;</code>
     */
    com.google.protobuf.ByteString getChunk();
  }
  /**
   * Protobuf type {@code com.rasp.fs.protobuf.SInputChunk}
   */
  public static final class SInputChunk extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.rasp.fs.protobuf.SInputChunk)
      SInputChunkOrBuilder {
    // Use SInputChunk.newBuilder() to construct.
    private SInputChunk(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SInputChunk(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SInputChunk defaultInstance;
    public static SInputChunk getDefaultInstance() {
      return defaultInstance;
    }

    public SInputChunk getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SInputChunk(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              chunk_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rasp.fs.SInputSplitProtos.internal_static_com_rasp_fs_protobuf_SInputChunk_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rasp.fs.SInputSplitProtos.internal_static_com_rasp_fs_protobuf_SInputChunk_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rasp.fs.SInputSplitProtos.SInputChunk.class, com.rasp.fs.SInputSplitProtos.SInputChunk.Builder.class);
    }

    public static com.google.protobuf.Parser<SInputChunk> PARSER =
        new com.google.protobuf.AbstractParser<SInputChunk>() {
      public SInputChunk parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SInputChunk(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SInputChunk> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int CHUNK_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString chunk_;
    /**
     * <code>required bytes chunk = 1;</code>
     */
    public boolean hasChunk() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes chunk = 1;</code>
     */
    public com.google.protobuf.ByteString getChunk() {
      return chunk_;
    }

    private void initFields() {
      chunk_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasChunk()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, chunk_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, chunk_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.rasp.fs.SInputSplitProtos.SInputChunk parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rasp.fs.SInputSplitProtos.SInputChunk parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rasp.fs.SInputSplitProtos.SInputChunk parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rasp.fs.SInputSplitProtos.SInputChunk parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rasp.fs.SInputSplitProtos.SInputChunk parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.rasp.fs.SInputSplitProtos.SInputChunk parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.rasp.fs.SInputSplitProtos.SInputChunk parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.rasp.fs.SInputSplitProtos.SInputChunk parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.rasp.fs.SInputSplitProtos.SInputChunk parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.rasp.fs.SInputSplitProtos.SInputChunk parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.rasp.fs.SInputSplitProtos.SInputChunk prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.rasp.fs.protobuf.SInputChunk}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.rasp.fs.protobuf.SInputChunk)
        com.rasp.fs.SInputSplitProtos.SInputChunkOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.rasp.fs.SInputSplitProtos.internal_static_com_rasp_fs_protobuf_SInputChunk_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.rasp.fs.SInputSplitProtos.internal_static_com_rasp_fs_protobuf_SInputChunk_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.rasp.fs.SInputSplitProtos.SInputChunk.class, com.rasp.fs.SInputSplitProtos.SInputChunk.Builder.class);
      }

      // Construct using com.rasp.fs.SInputSplitProtos.SInputChunk.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        chunk_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.rasp.fs.SInputSplitProtos.internal_static_com_rasp_fs_protobuf_SInputChunk_descriptor;
      }

      public com.rasp.fs.SInputSplitProtos.SInputChunk getDefaultInstanceForType() {
        return com.rasp.fs.SInputSplitProtos.SInputChunk.getDefaultInstance();
      }

      public com.rasp.fs.SInputSplitProtos.SInputChunk build() {
        com.rasp.fs.SInputSplitProtos.SInputChunk result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.rasp.fs.SInputSplitProtos.SInputChunk buildPartial() {
        com.rasp.fs.SInputSplitProtos.SInputChunk result = new com.rasp.fs.SInputSplitProtos.SInputChunk(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.chunk_ = chunk_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.rasp.fs.SInputSplitProtos.SInputChunk) {
          return mergeFrom((com.rasp.fs.SInputSplitProtos.SInputChunk)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.rasp.fs.SInputSplitProtos.SInputChunk other) {
        if (other == com.rasp.fs.SInputSplitProtos.SInputChunk.getDefaultInstance()) return this;
        if (other.hasChunk()) {
          setChunk(other.getChunk());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasChunk()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.rasp.fs.SInputSplitProtos.SInputChunk parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.rasp.fs.SInputSplitProtos.SInputChunk) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString chunk_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes chunk = 1;</code>
       */
      public boolean hasChunk() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes chunk = 1;</code>
       */
      public com.google.protobuf.ByteString getChunk() {
        return chunk_;
      }
      /**
       * <code>required bytes chunk = 1;</code>
       */
      public Builder setChunk(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        chunk_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes chunk = 1;</code>
       */
      public Builder clearChunk() {
        bitField0_ = (bitField0_ & ~0x00000001);
        chunk_ = getDefaultInstance().getChunk();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.rasp.fs.protobuf.SInputChunk)
    }

    static {
      defaultInstance = new SInputChunk(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.rasp.fs.protobuf.SInputChunk)
  }

  public interface TransferResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.rasp.fs.protobuf.TransferResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string status = 1;</code>
     */
    boolean hasStatus();
    /**
     * <code>optional string status = 1;</code>
     */
    java.lang.String getStatus();
    /**
     * <code>optional string status = 1;</code>
     */
    com.google.protobuf.ByteString
        getStatusBytes();
  }
  /**
   * Protobuf type {@code com.rasp.fs.protobuf.TransferResponse}
   */
  public static final class TransferResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.rasp.fs.protobuf.TransferResponse)
      TransferResponseOrBuilder {
    // Use TransferResponse.newBuilder() to construct.
    private TransferResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TransferResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TransferResponse defaultInstance;
    public static TransferResponse getDefaultInstance() {
      return defaultInstance;
    }

    public TransferResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TransferResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              status_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rasp.fs.SInputSplitProtos.internal_static_com_rasp_fs_protobuf_TransferResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rasp.fs.SInputSplitProtos.internal_static_com_rasp_fs_protobuf_TransferResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rasp.fs.SInputSplitProtos.TransferResponse.class, com.rasp.fs.SInputSplitProtos.TransferResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<TransferResponse> PARSER =
        new com.google.protobuf.AbstractParser<TransferResponse>() {
      public TransferResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TransferResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TransferResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int STATUS_FIELD_NUMBER = 1;
    private java.lang.Object status_;
    /**
     * <code>optional string status = 1;</code>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string status = 1;</code>
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          status_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string status = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      status_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getStatusBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getStatusBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.rasp.fs.SInputSplitProtos.TransferResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rasp.fs.SInputSplitProtos.TransferResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rasp.fs.SInputSplitProtos.TransferResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rasp.fs.SInputSplitProtos.TransferResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rasp.fs.SInputSplitProtos.TransferResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.rasp.fs.SInputSplitProtos.TransferResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.rasp.fs.SInputSplitProtos.TransferResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.rasp.fs.SInputSplitProtos.TransferResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.rasp.fs.SInputSplitProtos.TransferResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.rasp.fs.SInputSplitProtos.TransferResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.rasp.fs.SInputSplitProtos.TransferResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.rasp.fs.protobuf.TransferResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.rasp.fs.protobuf.TransferResponse)
        com.rasp.fs.SInputSplitProtos.TransferResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.rasp.fs.SInputSplitProtos.internal_static_com_rasp_fs_protobuf_TransferResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.rasp.fs.SInputSplitProtos.internal_static_com_rasp_fs_protobuf_TransferResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.rasp.fs.SInputSplitProtos.TransferResponse.class, com.rasp.fs.SInputSplitProtos.TransferResponse.Builder.class);
      }

      // Construct using com.rasp.fs.SInputSplitProtos.TransferResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        status_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.rasp.fs.SInputSplitProtos.internal_static_com_rasp_fs_protobuf_TransferResponse_descriptor;
      }

      public com.rasp.fs.SInputSplitProtos.TransferResponse getDefaultInstanceForType() {
        return com.rasp.fs.SInputSplitProtos.TransferResponse.getDefaultInstance();
      }

      public com.rasp.fs.SInputSplitProtos.TransferResponse build() {
        com.rasp.fs.SInputSplitProtos.TransferResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.rasp.fs.SInputSplitProtos.TransferResponse buildPartial() {
        com.rasp.fs.SInputSplitProtos.TransferResponse result = new com.rasp.fs.SInputSplitProtos.TransferResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.status_ = status_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.rasp.fs.SInputSplitProtos.TransferResponse) {
          return mergeFrom((com.rasp.fs.SInputSplitProtos.TransferResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.rasp.fs.SInputSplitProtos.TransferResponse other) {
        if (other == com.rasp.fs.SInputSplitProtos.TransferResponse.getDefaultInstance()) return this;
        if (other.hasStatus()) {
          bitField0_ |= 0x00000001;
          status_ = other.status_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.rasp.fs.SInputSplitProtos.TransferResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.rasp.fs.SInputSplitProtos.TransferResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object status_ = "";
      /**
       * <code>optional string status = 1;</code>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string status = 1;</code>
       */
      public java.lang.String getStatus() {
        java.lang.Object ref = status_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            status_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string status = 1;</code>
       */
      public com.google.protobuf.ByteString
          getStatusBytes() {
        java.lang.Object ref = status_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          status_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string status = 1;</code>
       */
      public Builder setStatus(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string status = 1;</code>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = getDefaultInstance().getStatus();
        onChanged();
        return this;
      }
      /**
       * <code>optional string status = 1;</code>
       */
      public Builder setStatusBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        status_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.rasp.fs.protobuf.TransferResponse)
    }

    static {
      defaultInstance = new TransferResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.rasp.fs.protobuf.TransferResponse)
  }

  public interface VoidOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.rasp.fs.protobuf.Void)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code com.rasp.fs.protobuf.Void}
   */
  public static final class Void extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.rasp.fs.protobuf.Void)
      VoidOrBuilder {
    // Use Void.newBuilder() to construct.
    private Void(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Void(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Void defaultInstance;
    public static Void getDefaultInstance() {
      return defaultInstance;
    }

    public Void getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Void(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rasp.fs.SInputSplitProtos.internal_static_com_rasp_fs_protobuf_Void_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rasp.fs.SInputSplitProtos.internal_static_com_rasp_fs_protobuf_Void_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rasp.fs.SInputSplitProtos.Void.class, com.rasp.fs.SInputSplitProtos.Void.Builder.class);
    }

    public static com.google.protobuf.Parser<Void> PARSER =
        new com.google.protobuf.AbstractParser<Void>() {
      public Void parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Void(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Void> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.rasp.fs.SInputSplitProtos.Void parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rasp.fs.SInputSplitProtos.Void parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rasp.fs.SInputSplitProtos.Void parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rasp.fs.SInputSplitProtos.Void parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rasp.fs.SInputSplitProtos.Void parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.rasp.fs.SInputSplitProtos.Void parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.rasp.fs.SInputSplitProtos.Void parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.rasp.fs.SInputSplitProtos.Void parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.rasp.fs.SInputSplitProtos.Void parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.rasp.fs.SInputSplitProtos.Void parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.rasp.fs.SInputSplitProtos.Void prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.rasp.fs.protobuf.Void}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.rasp.fs.protobuf.Void)
        com.rasp.fs.SInputSplitProtos.VoidOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.rasp.fs.SInputSplitProtos.internal_static_com_rasp_fs_protobuf_Void_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.rasp.fs.SInputSplitProtos.internal_static_com_rasp_fs_protobuf_Void_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.rasp.fs.SInputSplitProtos.Void.class, com.rasp.fs.SInputSplitProtos.Void.Builder.class);
      }

      // Construct using com.rasp.fs.SInputSplitProtos.Void.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.rasp.fs.SInputSplitProtos.internal_static_com_rasp_fs_protobuf_Void_descriptor;
      }

      public com.rasp.fs.SInputSplitProtos.Void getDefaultInstanceForType() {
        return com.rasp.fs.SInputSplitProtos.Void.getDefaultInstance();
      }

      public com.rasp.fs.SInputSplitProtos.Void build() {
        com.rasp.fs.SInputSplitProtos.Void result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.rasp.fs.SInputSplitProtos.Void buildPartial() {
        com.rasp.fs.SInputSplitProtos.Void result = new com.rasp.fs.SInputSplitProtos.Void(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.rasp.fs.SInputSplitProtos.Void) {
          return mergeFrom((com.rasp.fs.SInputSplitProtos.Void)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.rasp.fs.SInputSplitProtos.Void other) {
        if (other == com.rasp.fs.SInputSplitProtos.Void.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.rasp.fs.SInputSplitProtos.Void parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.rasp.fs.SInputSplitProtos.Void) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.rasp.fs.protobuf.Void)
    }

    static {
      defaultInstance = new Void(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.rasp.fs.protobuf.Void)
  }

  /**
   * Protobuf service {@code com.rasp.fs.protobuf.DataTransferService}
   */
  public static abstract class DataTransferService
      implements com.google.protobuf.Service {
    protected DataTransferService() {}

    public interface Interface {
      /**
       * <code>rpc sendInputSplit(.com.rasp.fs.protobuf.SInputSplit) returns (.com.rasp.fs.protobuf.TransferResponse);</code>
       */
      public abstract void sendInputSplit(
          com.google.protobuf.RpcController controller,
          com.rasp.fs.SInputSplitProtos.SInputSplit request,
          com.google.protobuf.RpcCallback<com.rasp.fs.SInputSplitProtos.TransferResponse> done);

      /**
       * <code>rpc sendChunk(.com.rasp.fs.protobuf.SInputChunk) returns (.com.rasp.fs.protobuf.TransferResponse);</code>
       */
      public abstract void sendChunk(
          com.google.protobuf.RpcController controller,
          com.rasp.fs.SInputSplitProtos.SInputChunk request,
          com.google.protobuf.RpcCallback<com.rasp.fs.SInputSplitProtos.TransferResponse> done);

      /**
       * <code>rpc closeInputSplit(.com.rasp.fs.protobuf.Void) returns (.com.rasp.fs.protobuf.Void);</code>
       */
      public abstract void closeInputSplit(
          com.google.protobuf.RpcController controller,
          com.rasp.fs.SInputSplitProtos.Void request,
          com.google.protobuf.RpcCallback<com.rasp.fs.SInputSplitProtos.Void> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new DataTransferService() {
        @java.lang.Override
        public  void sendInputSplit(
            com.google.protobuf.RpcController controller,
            com.rasp.fs.SInputSplitProtos.SInputSplit request,
            com.google.protobuf.RpcCallback<com.rasp.fs.SInputSplitProtos.TransferResponse> done) {
          impl.sendInputSplit(controller, request, done);
        }

        @java.lang.Override
        public  void sendChunk(
            com.google.protobuf.RpcController controller,
            com.rasp.fs.SInputSplitProtos.SInputChunk request,
            com.google.protobuf.RpcCallback<com.rasp.fs.SInputSplitProtos.TransferResponse> done) {
          impl.sendChunk(controller, request, done);
        }

        @java.lang.Override
        public  void closeInputSplit(
            com.google.protobuf.RpcController controller,
            com.rasp.fs.SInputSplitProtos.Void request,
            com.google.protobuf.RpcCallback<com.rasp.fs.SInputSplitProtos.Void> done) {
          impl.closeInputSplit(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.sendInputSplit(controller, (com.rasp.fs.SInputSplitProtos.SInputSplit)request);
            case 1:
              return impl.sendChunk(controller, (com.rasp.fs.SInputSplitProtos.SInputChunk)request);
            case 2:
              return impl.closeInputSplit(controller, (com.rasp.fs.SInputSplitProtos.Void)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.rasp.fs.SInputSplitProtos.SInputSplit.getDefaultInstance();
            case 1:
              return com.rasp.fs.SInputSplitProtos.SInputChunk.getDefaultInstance();
            case 2:
              return com.rasp.fs.SInputSplitProtos.Void.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.rasp.fs.SInputSplitProtos.TransferResponse.getDefaultInstance();
            case 1:
              return com.rasp.fs.SInputSplitProtos.TransferResponse.getDefaultInstance();
            case 2:
              return com.rasp.fs.SInputSplitProtos.Void.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc sendInputSplit(.com.rasp.fs.protobuf.SInputSplit) returns (.com.rasp.fs.protobuf.TransferResponse);</code>
     */
    public abstract void sendInputSplit(
        com.google.protobuf.RpcController controller,
        com.rasp.fs.SInputSplitProtos.SInputSplit request,
        com.google.protobuf.RpcCallback<com.rasp.fs.SInputSplitProtos.TransferResponse> done);

    /**
     * <code>rpc sendChunk(.com.rasp.fs.protobuf.SInputChunk) returns (.com.rasp.fs.protobuf.TransferResponse);</code>
     */
    public abstract void sendChunk(
        com.google.protobuf.RpcController controller,
        com.rasp.fs.SInputSplitProtos.SInputChunk request,
        com.google.protobuf.RpcCallback<com.rasp.fs.SInputSplitProtos.TransferResponse> done);

    /**
     * <code>rpc closeInputSplit(.com.rasp.fs.protobuf.Void) returns (.com.rasp.fs.protobuf.Void);</code>
     */
    public abstract void closeInputSplit(
        com.google.protobuf.RpcController controller,
        com.rasp.fs.SInputSplitProtos.Void request,
        com.google.protobuf.RpcCallback<com.rasp.fs.SInputSplitProtos.Void> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return com.rasp.fs.SInputSplitProtos.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.sendInputSplit(controller, (com.rasp.fs.SInputSplitProtos.SInputSplit)request,
            com.google.protobuf.RpcUtil.<com.rasp.fs.SInputSplitProtos.TransferResponse>specializeCallback(
              done));
          return;
        case 1:
          this.sendChunk(controller, (com.rasp.fs.SInputSplitProtos.SInputChunk)request,
            com.google.protobuf.RpcUtil.<com.rasp.fs.SInputSplitProtos.TransferResponse>specializeCallback(
              done));
          return;
        case 2:
          this.closeInputSplit(controller, (com.rasp.fs.SInputSplitProtos.Void)request,
            com.google.protobuf.RpcUtil.<com.rasp.fs.SInputSplitProtos.Void>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.rasp.fs.SInputSplitProtos.SInputSplit.getDefaultInstance();
        case 1:
          return com.rasp.fs.SInputSplitProtos.SInputChunk.getDefaultInstance();
        case 2:
          return com.rasp.fs.SInputSplitProtos.Void.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.rasp.fs.SInputSplitProtos.TransferResponse.getDefaultInstance();
        case 1:
          return com.rasp.fs.SInputSplitProtos.TransferResponse.getDefaultInstance();
        case 2:
          return com.rasp.fs.SInputSplitProtos.Void.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends com.rasp.fs.SInputSplitProtos.DataTransferService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void sendInputSplit(
          com.google.protobuf.RpcController controller,
          com.rasp.fs.SInputSplitProtos.SInputSplit request,
          com.google.protobuf.RpcCallback<com.rasp.fs.SInputSplitProtos.TransferResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.rasp.fs.SInputSplitProtos.TransferResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            com.rasp.fs.SInputSplitProtos.TransferResponse.class,
            com.rasp.fs.SInputSplitProtos.TransferResponse.getDefaultInstance()));
      }

      public  void sendChunk(
          com.google.protobuf.RpcController controller,
          com.rasp.fs.SInputSplitProtos.SInputChunk request,
          com.google.protobuf.RpcCallback<com.rasp.fs.SInputSplitProtos.TransferResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(1),
          controller,
          request,
          com.rasp.fs.SInputSplitProtos.TransferResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            com.rasp.fs.SInputSplitProtos.TransferResponse.class,
            com.rasp.fs.SInputSplitProtos.TransferResponse.getDefaultInstance()));
      }

      public  void closeInputSplit(
          com.google.protobuf.RpcController controller,
          com.rasp.fs.SInputSplitProtos.Void request,
          com.google.protobuf.RpcCallback<com.rasp.fs.SInputSplitProtos.Void> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(2),
          controller,
          request,
          com.rasp.fs.SInputSplitProtos.Void.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            com.rasp.fs.SInputSplitProtos.Void.class,
            com.rasp.fs.SInputSplitProtos.Void.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public com.rasp.fs.SInputSplitProtos.TransferResponse sendInputSplit(
          com.google.protobuf.RpcController controller,
          com.rasp.fs.SInputSplitProtos.SInputSplit request)
          throws com.google.protobuf.ServiceException;

      public com.rasp.fs.SInputSplitProtos.TransferResponse sendChunk(
          com.google.protobuf.RpcController controller,
          com.rasp.fs.SInputSplitProtos.SInputChunk request)
          throws com.google.protobuf.ServiceException;

      public com.rasp.fs.SInputSplitProtos.Void closeInputSplit(
          com.google.protobuf.RpcController controller,
          com.rasp.fs.SInputSplitProtos.Void request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public com.rasp.fs.SInputSplitProtos.TransferResponse sendInputSplit(
          com.google.protobuf.RpcController controller,
          com.rasp.fs.SInputSplitProtos.SInputSplit request)
          throws com.google.protobuf.ServiceException {
        return (com.rasp.fs.SInputSplitProtos.TransferResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.rasp.fs.SInputSplitProtos.TransferResponse.getDefaultInstance());
      }


      public com.rasp.fs.SInputSplitProtos.TransferResponse sendChunk(
          com.google.protobuf.RpcController controller,
          com.rasp.fs.SInputSplitProtos.SInputChunk request)
          throws com.google.protobuf.ServiceException {
        return (com.rasp.fs.SInputSplitProtos.TransferResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(1),
          controller,
          request,
          com.rasp.fs.SInputSplitProtos.TransferResponse.getDefaultInstance());
      }


      public com.rasp.fs.SInputSplitProtos.Void closeInputSplit(
          com.google.protobuf.RpcController controller,
          com.rasp.fs.SInputSplitProtos.Void request)
          throws com.google.protobuf.ServiceException {
        return (com.rasp.fs.SInputSplitProtos.Void) channel.callBlockingMethod(
          getDescriptor().getMethods().get(2),
          controller,
          request,
          com.rasp.fs.SInputSplitProtos.Void.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:com.rasp.fs.protobuf.DataTransferService)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_rasp_fs_protobuf_SInputSplit_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_rasp_fs_protobuf_SInputSplit_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_rasp_fs_protobuf_SInputChunk_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_rasp_fs_protobuf_SInputChunk_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_rasp_fs_protobuf_TransferResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_rasp_fs_protobuf_TransferResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_rasp_fs_protobuf_Void_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_rasp_fs_protobuf_Void_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021sinputsplit.proto\022\024com.rasp.fs.protobu" +
      "f\"L\n\013SInputSplit\022\013\n\003idx\030\001 \002(\005\022\016\n\006offset\030" +
      "\002 \002(\003\022\016\n\006length\030\003 \002(\003\022\020\n\010location\030\004 \002(\t\"" +
      "\034\n\013SInputChunk\022\r\n\005chunk\030\001 \002(\014\"\"\n\020Transfe" +
      "rResponse\022\016\n\006status\030\001 \001(\t\"\006\n\004Void2\225\002\n\023Da" +
      "taTransferService\022[\n\016sendInputSplit\022!.co" +
      "m.rasp.fs.protobuf.SInputSplit\032&.com.ras" +
      "p.fs.protobuf.TransferResponse\022V\n\tsendCh" +
      "unk\022!.com.rasp.fs.protobuf.SInputChunk\032&" +
      ".com.rasp.fs.protobuf.TransferResponse\022I",
      "\n\017closeInputSplit\022\032.com.rasp.fs.protobuf" +
      ".Void\032\032.com.rasp.fs.protobuf.VoidB#\n\013com" +
      ".rasp.fsB\021SInputSplitProtos\210\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_rasp_fs_protobuf_SInputSplit_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_rasp_fs_protobuf_SInputSplit_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_rasp_fs_protobuf_SInputSplit_descriptor,
        new java.lang.String[] { "Idx", "Offset", "Length", "Location", });
    internal_static_com_rasp_fs_protobuf_SInputChunk_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_rasp_fs_protobuf_SInputChunk_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_rasp_fs_protobuf_SInputChunk_descriptor,
        new java.lang.String[] { "Chunk", });
    internal_static_com_rasp_fs_protobuf_TransferResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_rasp_fs_protobuf_TransferResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_rasp_fs_protobuf_TransferResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_com_rasp_fs_protobuf_Void_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_rasp_fs_protobuf_Void_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_rasp_fs_protobuf_Void_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
