// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stask.proto

package com.rasp.fs;

public final class STaskProtos {
  private STaskProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface STaskOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.rasp.utils.protobuf.STask)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>required string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>required string jobId = 2;</code>
     */
    boolean hasJobId();
    /**
     * <code>required string jobId = 2;</code>
     */
    java.lang.String getJobId();
    /**
     * <code>required string jobId = 2;</code>
     */
    com.google.protobuf.ByteString
        getJobIdBytes();

    /**
     * <code>required int32 inputSplitId = 3;</code>
     */
    boolean hasInputSplitId();
    /**
     * <code>required int32 inputSplitId = 3;</code>
     */
    int getInputSplitId();

    /**
     * <code>required string className = 4;</code>
     */
    boolean hasClassName();
    /**
     * <code>required string className = 4;</code>
     */
    java.lang.String getClassName();
    /**
     * <code>required string className = 4;</code>
     */
    com.google.protobuf.ByteString
        getClassNameBytes();

    /**
     * <code>required .com.rasp.utils.protobuf.STask.STaskType taskType = 5;</code>
     */
    boolean hasTaskType();
    /**
     * <code>required .com.rasp.utils.protobuf.STask.STaskType taskType = 5;</code>
     */
    com.rasp.fs.STaskProtos.STask.STaskType getTaskType();
  }
  /**
   * Protobuf type {@code com.rasp.utils.protobuf.STask}
   */
  public static final class STask extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.rasp.utils.protobuf.STask)
      STaskOrBuilder {
    // Use STask.newBuilder() to construct.
    private STask(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private STask(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final STask defaultInstance;
    public static STask getDefaultInstance() {
      return defaultInstance;
    }

    public STask getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private STask(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              id_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              jobId_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              inputSplitId_ = input.readInt32();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              className_ = bs;
              break;
            }
            case 40: {
              int rawValue = input.readEnum();
              com.rasp.fs.STaskProtos.STask.STaskType value = com.rasp.fs.STaskProtos.STask.STaskType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(5, rawValue);
              } else {
                bitField0_ |= 0x00000010;
                taskType_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rasp.fs.STaskProtos.internal_static_com_rasp_fs_protobuf_STask_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rasp.fs.STaskProtos.internal_static_com_rasp_fs_protobuf_STask_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rasp.fs.STaskProtos.STask.class, com.rasp.fs.STaskProtos.STask.Builder.class);
    }

    public static com.google.protobuf.Parser<STask> PARSER =
        new com.google.protobuf.AbstractParser<STask>() {
      public STask parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new STask(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<STask> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code com.rasp.utils.protobuf.STask.STaskType}
     */
    public enum STaskType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>MAPPER = 1;</code>
       */
      MAPPER(0, 1),
      /**
       * <code>REDUCER = 2;</code>
       */
      REDUCER(1, 2),
      ;

      /**
       * <code>MAPPER = 1;</code>
       */
      public static final int MAPPER_VALUE = 1;
      /**
       * <code>REDUCER = 2;</code>
       */
      public static final int REDUCER_VALUE = 2;


      public final int getNumber() { return value; }

      public static STaskType valueOf(int value) {
        switch (value) {
          case 1: return MAPPER;
          case 2: return REDUCER;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<STaskType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<STaskType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<STaskType>() {
              public STaskType findValueByNumber(int number) {
                return STaskType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.rasp.fs.STaskProtos.STask.getDescriptor().getEnumTypes().get(0);
      }

      private static final STaskType[] VALUES = values();

      public static STaskType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private STaskType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.rasp.utils.protobuf.STask.STaskType)
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    /**
     * <code>required string id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int JOBID_FIELD_NUMBER = 2;
    private java.lang.Object jobId_;
    /**
     * <code>required string jobId = 2;</code>
     */
    public boolean hasJobId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string jobId = 2;</code>
     */
    public java.lang.String getJobId() {
      java.lang.Object ref = jobId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          jobId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string jobId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getJobIdBytes() {
      java.lang.Object ref = jobId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        jobId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INPUTSPLITID_FIELD_NUMBER = 3;
    private int inputSplitId_;
    /**
     * <code>required int32 inputSplitId = 3;</code>
     */
    public boolean hasInputSplitId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 inputSplitId = 3;</code>
     */
    public int getInputSplitId() {
      return inputSplitId_;
    }

    public static final int CLASSNAME_FIELD_NUMBER = 4;
    private java.lang.Object className_;
    /**
     * <code>required string className = 4;</code>
     */
    public boolean hasClassName() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string className = 4;</code>
     */
    public java.lang.String getClassName() {
      java.lang.Object ref = className_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          className_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string className = 4;</code>
     */
    public com.google.protobuf.ByteString
        getClassNameBytes() {
      java.lang.Object ref = className_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        className_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TASKTYPE_FIELD_NUMBER = 5;
    private com.rasp.fs.STaskProtos.STask.STaskType taskType_;
    /**
     * <code>required .com.rasp.utils.protobuf.STask.STaskType taskType = 5;</code>
     */
    public boolean hasTaskType() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required .com.rasp.utils.protobuf.STask.STaskType taskType = 5;</code>
     */
    public com.rasp.fs.STaskProtos.STask.STaskType getTaskType() {
      return taskType_;
    }

    private void initFields() {
      id_ = "";
      jobId_ = "";
      inputSplitId_ = 0;
      className_ = "";
      taskType_ = com.rasp.fs.STaskProtos.STask.STaskType.MAPPER;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasJobId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasInputSplitId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasClassName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTaskType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getJobIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, inputSplitId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getClassNameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeEnum(5, taskType_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getJobIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, inputSplitId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getClassNameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, taskType_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.rasp.fs.STaskProtos.STask parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rasp.fs.STaskProtos.STask parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rasp.fs.STaskProtos.STask parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rasp.fs.STaskProtos.STask parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rasp.fs.STaskProtos.STask parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.rasp.fs.STaskProtos.STask parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.rasp.fs.STaskProtos.STask parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.rasp.fs.STaskProtos.STask parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.rasp.fs.STaskProtos.STask parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.rasp.fs.STaskProtos.STask parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.rasp.fs.STaskProtos.STask prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.rasp.utils.protobuf.STask}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.rasp.utils.protobuf.STask)
        com.rasp.fs.STaskProtos.STaskOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.rasp.fs.STaskProtos.internal_static_com_rasp_fs_protobuf_STask_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.rasp.fs.STaskProtos.internal_static_com_rasp_fs_protobuf_STask_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.rasp.fs.STaskProtos.STask.class, com.rasp.fs.STaskProtos.STask.Builder.class);
      }

      // Construct using com.rasp.fs.STaskProtos.STask.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        jobId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        inputSplitId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        className_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        taskType_ = com.rasp.fs.STaskProtos.STask.STaskType.MAPPER;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.rasp.fs.STaskProtos.internal_static_com_rasp_fs_protobuf_STask_descriptor;
      }

      public com.rasp.fs.STaskProtos.STask getDefaultInstanceForType() {
        return com.rasp.fs.STaskProtos.STask.getDefaultInstance();
      }

      public com.rasp.fs.STaskProtos.STask build() {
        com.rasp.fs.STaskProtos.STask result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.rasp.fs.STaskProtos.STask buildPartial() {
        com.rasp.fs.STaskProtos.STask result = new com.rasp.fs.STaskProtos.STask(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.jobId_ = jobId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.inputSplitId_ = inputSplitId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.className_ = className_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.taskType_ = taskType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.rasp.fs.STaskProtos.STask) {
          return mergeFrom((com.rasp.fs.STaskProtos.STask)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.rasp.fs.STaskProtos.STask other) {
        if (other == com.rasp.fs.STaskProtos.STask.getDefaultInstance()) return this;
        if (other.hasId()) {
          bitField0_ |= 0x00000001;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasJobId()) {
          bitField0_ |= 0x00000002;
          jobId_ = other.jobId_;
          onChanged();
        }
        if (other.hasInputSplitId()) {
          setInputSplitId(other.getInputSplitId());
        }
        if (other.hasClassName()) {
          bitField0_ |= 0x00000008;
          className_ = other.className_;
          onChanged();
        }
        if (other.hasTaskType()) {
          setTaskType(other.getTaskType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasJobId()) {
          
          return false;
        }
        if (!hasInputSplitId()) {
          
          return false;
        }
        if (!hasClassName()) {
          
          return false;
        }
        if (!hasTaskType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.rasp.fs.STaskProtos.STask parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.rasp.fs.STaskProtos.STask) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>required string id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            id_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object jobId_ = "";
      /**
       * <code>required string jobId = 2;</code>
       */
      public boolean hasJobId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string jobId = 2;</code>
       */
      public java.lang.String getJobId() {
        java.lang.Object ref = jobId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            jobId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string jobId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getJobIdBytes() {
        java.lang.Object ref = jobId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          jobId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string jobId = 2;</code>
       */
      public Builder setJobId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        jobId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string jobId = 2;</code>
       */
      public Builder clearJobId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        jobId_ = getDefaultInstance().getJobId();
        onChanged();
        return this;
      }
      /**
       * <code>required string jobId = 2;</code>
       */
      public Builder setJobIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        jobId_ = value;
        onChanged();
        return this;
      }

      private int inputSplitId_ ;
      /**
       * <code>required int32 inputSplitId = 3;</code>
       */
      public boolean hasInputSplitId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 inputSplitId = 3;</code>
       */
      public int getInputSplitId() {
        return inputSplitId_;
      }
      /**
       * <code>required int32 inputSplitId = 3;</code>
       */
      public Builder setInputSplitId(int value) {
        bitField0_ |= 0x00000004;
        inputSplitId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 inputSplitId = 3;</code>
       */
      public Builder clearInputSplitId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        inputSplitId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object className_ = "";
      /**
       * <code>required string className = 4;</code>
       */
      public boolean hasClassName() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string className = 4;</code>
       */
      public java.lang.String getClassName() {
        java.lang.Object ref = className_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            className_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string className = 4;</code>
       */
      public com.google.protobuf.ByteString
          getClassNameBytes() {
        java.lang.Object ref = className_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          className_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string className = 4;</code>
       */
      public Builder setClassName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        className_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string className = 4;</code>
       */
      public Builder clearClassName() {
        bitField0_ = (bitField0_ & ~0x00000008);
        className_ = getDefaultInstance().getClassName();
        onChanged();
        return this;
      }
      /**
       * <code>required string className = 4;</code>
       */
      public Builder setClassNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        className_ = value;
        onChanged();
        return this;
      }

      private com.rasp.fs.STaskProtos.STask.STaskType taskType_ = com.rasp.fs.STaskProtos.STask.STaskType.MAPPER;
      /**
       * <code>required .com.rasp.utils.protobuf.STask.STaskType taskType = 5;</code>
       */
      public boolean hasTaskType() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required .com.rasp.utils.protobuf.STask.STaskType taskType = 5;</code>
       */
      public com.rasp.fs.STaskProtos.STask.STaskType getTaskType() {
        return taskType_;
      }
      /**
       * <code>required .com.rasp.utils.protobuf.STask.STaskType taskType = 5;</code>
       */
      public Builder setTaskType(com.rasp.fs.STaskProtos.STask.STaskType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        taskType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .com.rasp.utils.protobuf.STask.STaskType taskType = 5;</code>
       */
      public Builder clearTaskType() {
        bitField0_ = (bitField0_ & ~0x00000010);
        taskType_ = com.rasp.fs.STaskProtos.STask.STaskType.MAPPER;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.rasp.utils.protobuf.STask)
    }

    static {
      defaultInstance = new STask(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.rasp.utils.protobuf.STask)
  }

  public interface TransferResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.rasp.utils.protobuf.TransferResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string status = 1;</code>
     */
    boolean hasStatus();
    /**
     * <code>optional string status = 1;</code>
     */
    java.lang.String getStatus();
    /**
     * <code>optional string status = 1;</code>
     */
    com.google.protobuf.ByteString
        getStatusBytes();
  }
  /**
   * Protobuf type {@code com.rasp.utils.protobuf.TransferResponse}
   */
  public static final class TransferResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.rasp.utils.protobuf.TransferResponse)
      TransferResponseOrBuilder {
    // Use TransferResponse.newBuilder() to construct.
    private TransferResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TransferResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TransferResponse defaultInstance;
    public static TransferResponse getDefaultInstance() {
      return defaultInstance;
    }

    public TransferResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TransferResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              status_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rasp.fs.STaskProtos.internal_static_com_rasp_fs_protobuf_TransferResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rasp.fs.STaskProtos.internal_static_com_rasp_fs_protobuf_TransferResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rasp.fs.STaskProtos.TransferResponse.class, com.rasp.fs.STaskProtos.TransferResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<TransferResponse> PARSER =
        new com.google.protobuf.AbstractParser<TransferResponse>() {
      public TransferResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TransferResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TransferResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int STATUS_FIELD_NUMBER = 1;
    private java.lang.Object status_;
    /**
     * <code>optional string status = 1;</code>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string status = 1;</code>
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          status_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string status = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      status_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getStatusBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getStatusBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.rasp.fs.STaskProtos.TransferResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rasp.fs.STaskProtos.TransferResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rasp.fs.STaskProtos.TransferResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rasp.fs.STaskProtos.TransferResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rasp.fs.STaskProtos.TransferResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.rasp.fs.STaskProtos.TransferResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.rasp.fs.STaskProtos.TransferResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.rasp.fs.STaskProtos.TransferResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.rasp.fs.STaskProtos.TransferResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.rasp.fs.STaskProtos.TransferResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.rasp.fs.STaskProtos.TransferResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.rasp.utils.protobuf.TransferResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.rasp.utils.protobuf.TransferResponse)
        com.rasp.fs.STaskProtos.TransferResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.rasp.fs.STaskProtos.internal_static_com_rasp_fs_protobuf_TransferResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.rasp.fs.STaskProtos.internal_static_com_rasp_fs_protobuf_TransferResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.rasp.fs.STaskProtos.TransferResponse.class, com.rasp.fs.STaskProtos.TransferResponse.Builder.class);
      }

      // Construct using com.rasp.fs.STaskProtos.TransferResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        status_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.rasp.fs.STaskProtos.internal_static_com_rasp_fs_protobuf_TransferResponse_descriptor;
      }

      public com.rasp.fs.STaskProtos.TransferResponse getDefaultInstanceForType() {
        return com.rasp.fs.STaskProtos.TransferResponse.getDefaultInstance();
      }

      public com.rasp.fs.STaskProtos.TransferResponse build() {
        com.rasp.fs.STaskProtos.TransferResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.rasp.fs.STaskProtos.TransferResponse buildPartial() {
        com.rasp.fs.STaskProtos.TransferResponse result = new com.rasp.fs.STaskProtos.TransferResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.status_ = status_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.rasp.fs.STaskProtos.TransferResponse) {
          return mergeFrom((com.rasp.fs.STaskProtos.TransferResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.rasp.fs.STaskProtos.TransferResponse other) {
        if (other == com.rasp.fs.STaskProtos.TransferResponse.getDefaultInstance()) return this;
        if (other.hasStatus()) {
          bitField0_ |= 0x00000001;
          status_ = other.status_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.rasp.fs.STaskProtos.TransferResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.rasp.fs.STaskProtos.TransferResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object status_ = "";
      /**
       * <code>optional string status = 1;</code>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string status = 1;</code>
       */
      public java.lang.String getStatus() {
        java.lang.Object ref = status_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            status_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string status = 1;</code>
       */
      public com.google.protobuf.ByteString
          getStatusBytes() {
        java.lang.Object ref = status_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          status_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string status = 1;</code>
       */
      public Builder setStatus(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string status = 1;</code>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = getDefaultInstance().getStatus();
        onChanged();
        return this;
      }
      /**
       * <code>optional string status = 1;</code>
       */
      public Builder setStatusBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        status_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.rasp.utils.protobuf.TransferResponse)
    }

    static {
      defaultInstance = new TransferResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.rasp.utils.protobuf.TransferResponse)
  }

  /**
   * Protobuf service {@code com.rasp.utils.protobuf.TaskService}
   */
  public static abstract class TaskService
      implements com.google.protobuf.Service {
    protected TaskService() {}

    public interface Interface {
      /**
       * <code>rpc sendTask(.com.rasp.utils.protobuf.STask) returns (.com.rasp.utils.protobuf.TransferResponse);</code>
       */
      public abstract void sendTask(
          com.google.protobuf.RpcController controller,
          com.rasp.fs.STaskProtos.STask request,
          com.google.protobuf.RpcCallback<com.rasp.fs.STaskProtos.TransferResponse> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new TaskService() {
        @java.lang.Override
        public  void sendTask(
            com.google.protobuf.RpcController controller,
            com.rasp.fs.STaskProtos.STask request,
            com.google.protobuf.RpcCallback<com.rasp.fs.STaskProtos.TransferResponse> done) {
          impl.sendTask(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.sendTask(controller, (com.rasp.fs.STaskProtos.STask)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.rasp.fs.STaskProtos.STask.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.rasp.fs.STaskProtos.TransferResponse.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc sendTask(.com.rasp.utils.protobuf.STask) returns (.com.rasp.utils.protobuf.TransferResponse);</code>
     */
    public abstract void sendTask(
        com.google.protobuf.RpcController controller,
        com.rasp.fs.STaskProtos.STask request,
        com.google.protobuf.RpcCallback<com.rasp.fs.STaskProtos.TransferResponse> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return com.rasp.fs.STaskProtos.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.sendTask(controller, (com.rasp.fs.STaskProtos.STask)request,
            com.google.protobuf.RpcUtil.<com.rasp.fs.STaskProtos.TransferResponse>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.rasp.fs.STaskProtos.STask.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.rasp.fs.STaskProtos.TransferResponse.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends com.rasp.fs.STaskProtos.TaskService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void sendTask(
          com.google.protobuf.RpcController controller,
          com.rasp.fs.STaskProtos.STask request,
          com.google.protobuf.RpcCallback<com.rasp.fs.STaskProtos.TransferResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.rasp.fs.STaskProtos.TransferResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            com.rasp.fs.STaskProtos.TransferResponse.class,
            com.rasp.fs.STaskProtos.TransferResponse.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public com.rasp.fs.STaskProtos.TransferResponse sendTask(
          com.google.protobuf.RpcController controller,
          com.rasp.fs.STaskProtos.STask request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public com.rasp.fs.STaskProtos.TransferResponse sendTask(
          com.google.protobuf.RpcController controller,
          com.rasp.fs.STaskProtos.STask request)
          throws com.google.protobuf.ServiceException {
        return (com.rasp.fs.STaskProtos.TransferResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.rasp.fs.STaskProtos.TransferResponse.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:com.rasp.utils.protobuf.TaskService)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_rasp_fs_protobuf_STask_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_rasp_fs_protobuf_STask_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_rasp_fs_protobuf_TransferResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_rasp_fs_protobuf_TransferResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013stask.proto\022\024com.rasp.fs.protobuf\"\252\001\n\005" +
      "STask\022\n\n\002id\030\001 \002(\t\022\r\n\005jobId\030\002 \002(\t\022\024\n\014inpu" +
      "tSplitId\030\003 \002(\005\022\021\n\tclassName\030\004 \002(\t\0227\n\010tas" +
      "kType\030\005 \002(\0162%.com.rasp.utils.protobuf.STask" +
      ".STaskType\"$\n\tSTaskType\022\n\n\006MAPPER\020\001\022\013\n\007R" +
      "EDUCER\020\002\"\"\n\020TransferResponse\022\016\n\006status\030\001" +
      " \001(\t2^\n\013TaskService\022O\n\010sendTask\022\033.com.ra" +
      "sp.fs.protobuf.STask\032&.com.rasp.fs.proto" +
      "buf.TransferResponseB\035\n\013com.rasp.fsB\013STa" +
      "skProtos\210\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_rasp_fs_protobuf_STask_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_rasp_fs_protobuf_STask_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_rasp_fs_protobuf_STask_descriptor,
        new java.lang.String[] { "Id", "JobId", "InputSplitId", "ClassName", "TaskType", });
    internal_static_com_rasp_fs_protobuf_TransferResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_rasp_fs_protobuf_TransferResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_rasp_fs_protobuf_TransferResponse_descriptor,
        new java.lang.String[] { "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
